### ISSUE TITLE
Database Triger and Procedure 구현

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/naver_real_estate_crawling#14]
### SUMMARY
Data base 'Apartment DB'에 값이 추가될 때 추가, 삭제 기능 트리거로 구현
전체 갯수 체크해서 location DB에 넣는 프로시저 구현

### TODO

- [x] 트리거 추가 +1 구현
- [x] 트리거 삭제 -1 구현
- [x] Apartment DB에 갯수를 체크해서 location DB count 갯수를 넣는 프로시져 구현
