### ISSUE TITLE
accounts 확장시켜서 구현

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/naver_real_estate_crawling#2]
### Summary
accounts 파일을 한 개 만들어서 DB를 구성을 하고 manger로 해서 확장을 시켜줍니다.

<hr/>

### TODO
- [x] accounts 폴더 추가
- [x] migrate 및 migrations 하기
- [x] url.py 만들어서 설정
- [x] manager로 확장 시켜서 Model 구축

**Comment by wnstjd5408** [comment]
User 확장시켜서 login 구현
