### ISSUE TITLE
aplist 꾸미기 및 aptdetail Template  만들기

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/naver_real_estate_crawling#7]
### Summary
aplist 페이지 bootstrap을 이용해서 CSS 추가 그리고 aptdetail에 세부 페이지 구성을 합니다.

### TODO

- [x] aptlist 페이지 꾸미기
- [x] aptdetail 세부 페이지 구성
- [x] location 폴더에 views 기능 추가
