### ISSUE TITLE
Chart js를 이용해서 표 보여주기

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/naver_real_estate_crawling#8]
### Summary
Chart JS를 이용해서 aptlist 부분에 Chart js에서 Canvas 태그를 이용해서 차트 시각화를 해줍니다.

### TODO

- [x] Chart JS를 이용해서 Canvas 보여주기
- [x] Chart 값을 가공하기위해서 location 폴더의 view 부분 추가
- [ ] 여러 개의 인기 많은 아파트 순서대로 5개의 최근 매물 가격을 bar Chart를 이용해서 보여줍니다.

**Comment by wnstjd5408** [comment]
accounts 폴더에 BasketListView에서 List에서 수정을 해주었습니다.
Apartment list에서 보여주는거 추후에 예정입니다.
